<a href="https://colab.research.google.com/github/niranjankumarprajapati17-cmd/Machine-learning-pipeline-data-preprocessing-/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One-Hot-Encodings

In [27]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df=pd.read_csv("Housing.csv")
Housing_area_1hot=df[["area","bedrooms","bathrooms"]]
Housing_area_1hot
Cat_Encoder=OneHotEncoder()
Housing_area_1hot=Cat_Encoder.fit_transform(Housing_area_1hot)


In [130]:
print(Housing_area_1hot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
print(df)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating aircond

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [11]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished


In [12]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000


In [14]:
Housing_area_1hot.data

array([1., 1., 1., ..., 1., 1., 1.])

In [17]:
Housing_area_1hot.toarray() # Finding array

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
Housing_area_1hot.todense() # Dense array to direct

matrix([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
Cat_Encoder=OneHotEncoder(sparse_output=False) # Dense array
Housing_area_1hot=Cat_Encoder.fit_transform(df[["area","bedrooms","bathrooms"]])

In [30]:
print(Cat_Encoder)

OneHotEncoder(sparse_output=False)


In [31]:
print(Housing_area_1hot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [33]:
Cat_Encoder.categories_ # To check category order.

[array([ 1650,  1700,  1836,  1905,  1950,  2000,  2015,  2135,  2145,
         2160,  2175,  2176,  2275,  2325,  2398,  2400,  2430,  2475,
         2500,  2520,  2550,  2610,  2640,  2650,  2684,  2700,  2747,
         2787,  2800,  2817,  2835,  2850,  2856,  2870,  2880,  2910,
         2953,  2970,  2990,  3000,  3036,  3040,  3060,  3069,  3090,
         3100,  3120,  3150,  3162,  3180,  3185,  3210,  3240,  3264,
         3290,  3300,  3350,  3360,  3400,  3410,  3420,  3450,  3460,
         3480,  3500,  3510,  3512,  3520,  3540,  3570,  3584,  3600,
         3620,  3630,  3635,  3640,  3649,  3650,  3660,  3680,  3700,
         3720,  3745,  3750,  3760,  3780,  3792,  3800,  3816,  3840,
         3850,  3880,  3900,  3930,  3934,  3960,  3968,  3970,  3986,
         3990,  4000,  4032,  4040,  4046,  4050,  4075,  4079,  4080,
         4095,  4100,  4120,  4130,  4160,  4200,  4240,  4260,  4280,
         4300,  4320,  4340,  4350,  4352,  4360,  4370,  4400,  4410,
      

# Min-Max Scaling (Normalization)

In [38]:
from sklearn.preprocessing import MinMaxScaler

df=pd.read_excel("numpy_data.xlsx")
min_max=MinMaxScaler(feature_range=(-1,1))

# Select only numerical columns for scaling
numerical_cols = df.select_dtypes(include=['number']).columns
df_min_max=min_max.fit_transform(df[numerical_cols])

In [52]:
df # Print all data of xcel file

,Name,University,ATTENDANCE,RESULT,GRADE,TOTAL NUMBER
0,Bhupesh,IIT KANPUR,78,PASS,A+,90
1,Suresh,IIT BHU,69,PASS,B,80
2,Mukesh,IIT PATNA,79,FAIL,A,45
3,Denesh,IITM,94,PASS,B+,78
4,Nitesh,PSU,49,FAIL,C,34
5,Abhijay,PSIT,97,FAIL,D,42
6,Jatin(Gandhi),LPU,80,PASS,E,67
7,Sami,AMITY,60,FAIL,G,35
8,Amit,DU,27,PASS,D,56
9,Abishek,KGI,45,PASS,A+,90


In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Name          15 non-null     object
 1   University    15 non-null     object
 2   ATTENDANCE    15 non-null     int64 
 3   RESULT        15 non-null     object
 4   GRADE         15 non-null     object
 5   TOTAL NUMBER  15 non-null     int64 
dtypes: int64(2), object(4)
memory usage: 852.0+ bytes


In [43]:
df.GRADE

,GRADE
0,A+
1,B
2,A
3,B+
4,C
5,D
6,E
7,G
8,D
9,A+


In [44]:
df.describe()

,ATTENDANCE,TOTAL NUMBER
count,15.000000,15.000000
mean,67.066667,56.000000
std,22.069587,27.079249
min,27.000000,12.000000
25%,47.500000,34.500000
50%,70.000000,56.000000
75%,83.500000,80.000000
max,97.000000,90.000000


In [45]:
df.head()

,Name,University,ATTENDANCE,RESULT,GRADE,TOTAL NUMBER
0,Bhupesh,IIT KANPUR,78,PASS,A+,90
1,Suresh,IIT BHU,69,PASS,B,80
2,Mukesh,IIT PATNA,79,FAIL,A,45
3,Denesh,IITM,94,PASS,B+,78
4,Nitesh,PSU,49,FAIL,C,34


In [46]:
print(df)

             Name  University  ATTENDANCE RESULT GRADE  TOTAL NUMBER
0         Bhupesh  IIT KANPUR          78   PASS    A+            90
1          Suresh     IIT BHU          69   PASS     B            80
2          Mukesh   IIT PATNA          79   FAIL     A            45
3          Denesh        IITM          94   PASS    B+            78
4          Nitesh         PSU          49   FAIL     C            34
5         Abhijay        PSIT          97   FAIL     D            42
6   Jatin(Gandhi)         LPU          80   PASS     E            67
7            Sami       AMITY          60   FAIL     G            35
8            Amit          DU          27   PASS     D            56
9         Abishek         KGI          45   PASS    A+            90
10         Ashish        MPGI          36   FAIL    B+            80
11       Satendra          JP          46   PASS     A            85
12        Nishant        SKIM          87   FAIL     F            23
13       Shailesh        SISE     

In [47]:
print(min_max)

MinMaxScaler(feature_range=(-1, 1))


In [48]:
print(numerical_cols)

Index(['ATTENDANCE', 'TOTAL NUMBER'], dtype='object')


In [49]:
print(df_min_max)

[[ 0.45714286  1.        ]
 [ 0.2         0.74358974]
 [ 0.48571429 -0.15384615]
 [ 0.91428571  0.69230769]
 [-0.37142857 -0.43589744]
 [ 1.         -0.23076923]
 [ 0.51428571  0.41025641]
 [-0.05714286 -0.41025641]
 [-1.          0.12820513]
 [-0.48571429  1.        ]
 [-0.74285714  0.74358974]
 [-0.45714286  0.87179487]
 [ 0.71428571 -0.71794872]
 [ 0.77142857 -1.        ]
 [ 0.22857143 -0.71794872]]


# Standerdization (Z-score Scaling)

In [58]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

df=pd.read_csv("Housing.csv")

std_scaler=StandardScaler()
df_std_scaler=std_scaler.fit_transform(std_scaler.fit_transform(df[["area","bedrooms","bathrooms"]]))

In [59]:
print(df)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating aircond

In [60]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished


In [61]:
print(df_std_scaler)

[[ 1.04672629  1.40341936  1.42181174]
 [ 1.75700953  1.40341936  5.40580863]
 [ 2.21823241  0.04727831  1.42181174]
 ...
 [-0.70592066 -1.30886273 -0.57018671]
 [-1.03338891  0.04727831 -0.57018671]
 [-0.5998394   0.04727831 -0.57018671]]


In [66]:
df.index

RangeIndex(start=0, stop=545, step=1)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [70]:
df.get

<bound method NDFrame.get of         price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]>

In [71]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000


In [72]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished


In [73]:
std_scaler.mean_

array([-1.56449777e-16, -1.82524739e-16, -2.60749628e-17])

In [79]:
df_std_scaler.mean

<function ndarray.mean>

# Transformation pipeline

> Building a Numerical pipeline



In [93]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer # Corrected typo
from sklearn.preprocessing import StandardScaler
import pandas as pd

data=pd.read_csv("Housing.csv")

# The line data.fit_transform(data) is incorrect and not needed here.
# The pipeline will handle the fitting and transforming.

data_pipeline=Pipeline([
    ("impute",SimpleImputer(strategy="median")),
    ("standerdize",StandardScaler()),
])

# To use the pipeline, you would typically call fit_transform on your data,
# for example, data_processed = data_pipeline.fit_transform(data.select_dtypes(include=['number']))
# if you only want to process numerical columns.

In [94]:
print(data_pipeline)

Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                ('standerdize', StandardScaler())])


In [95]:
data_pipeline.fit_transform(data[['area','bedrooms','bathrooms']])

array([[ 1.04672629,  1.40341936,  1.42181174],
       [ 1.75700953,  1.40341936,  5.40580863],
       [ 2.21823241,  0.04727831,  1.42181174],
       ...,
       [-0.70592066, -1.30886273, -0.57018671],
       [-1.03338891,  0.04727831, -0.57018671],
       [-0.5998394 ,  0.04727831, -0.57018671]])

In [96]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished


In [97]:
from sklearn.pipeline import make_pipeline

data_pipeline=make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

In [98]:
data_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

In [100]:
make_pipeline()

Pipeline(steps=[])

In [101]:
make_pipeline

<function sklearn.pipeline.make_pipeline(*steps, memory=None, transform_input=None, verbose=False)>

# Using make_pipeline

In [119]:
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

data=pd.read_csv("Housing.csv")

# Re-initialize data_pipeline to ensure it's a Pipeline object
data_pipeline=make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

# The previous `data_pipeline` was defined to handle numerical columns.
# To avoid errors with categorical columns, we'll select only numerical ones for this pipeline.
# The column name '   guestroom   ' also had extra whitespace, which is corrected here.
# data_pipeline_transformed = data_pipeline.fit_transform(data[['area','bedrooms','bathrooms']])
# print(data_pipeline_transformed)

In [120]:
data_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

# Applying the pipeline

In [126]:
data_num_prepared=data_pipeline.fit_transform(data[['area']])
print(data_num_prepared[:20].round(10))

[[ 1.04672629]
 [ 1.75700953]
 [ 2.21823241]
 [ 1.08362412]
 [ 1.04672629]
 [ 1.08362412]
 [ 1.58174483]
 [ 5.09626319]
 [ 1.36035785]
 [ 0.27648408]
 [ 3.71259454]
 [ 0.3917898 ]
 [ 0.64546238]
 [-0.76126741]
 [ 1.22199098]
 [ 0.3917898 ]
 [ 0.66852353]
 [ 1.544847  ]
 [-0.25392224]
 [ 0.58550341]]


# Retrieving Feature Names

In [147]:
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

df=pd.read_csv('spotify_global_trends_2026.csv')

# Define a numerical pipeline
df_pipeline = make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

# Select the numerical columns from the spotify DataFrame for processing
# Based on common numerical columns in such datasets:
numerical_cols_spotify = ['streams', 'stream_change', '7day', 'days', 'viral_score']

# Apply the pipeline to transform the numerical data
data_transformed = df_pipeline.fit_transform(df[numerical_cols_spotify])

# Create a DataFrame from the transformed data with proper column names and index
df_streams_prepared=pd.DataFrame(
    data_transformed,
    columns=df_pipeline.get_feature_names_out(numerical_cols_spotify),
    index=df.index
)

In [149]:
df_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

In [148]:
df

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
174,Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
175,Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
176,Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen


In [150]:
data_transformed

array([[ 7.20491530e+00, -4.12746697e+00,  2.33578163e+00,
        -8.67561494e-01,  3.39146668e+00],
       [ 3.70612769e+00, -5.45796454e+00,  9.63581950e-01,
        -8.67561494e-01,  1.53905349e+00],
       [ 2.85709563e+00,  6.00704858e-01,  4.18705316e+00,
        -6.77575735e-01,  4.16108805e+00],
       [ 2.54689653e+00, -4.16254438e+00,  2.83040007e-01,
        -8.67561494e-01,  7.30205796e-01],
       [ 2.43557836e+00, -3.46593665e+00,  1.43239803e-01,
        -8.67561494e-01,  5.88235523e-01],
       [ 2.08439258e+00, -2.84850054e+00, -9.22017694e-02,
        -8.67561494e-01,  3.17915366e-01],
       [ 2.07579185e+00,  4.91209996e-02,  3.77774562e+00,
        -7.50647181e-01,  3.65857345e+00],
       [ 2.06028401e+00, -3.68266456e+00,  5.68175331e-03,
        -8.67561494e-01,  3.97854829e-01],
       [ 1.94681625e+00, -3.37961847e+00, -8.38622814e-02,
        -8.67561494e-01,  2.98878554e-01],
       [ 1.94157372e+00, -2.64802256e+00, -1.81364342e-01,
        -8.67561494e-01

In [151]:
df_streams_prepared

,streams,stream_change,7day,days,viral_score
0,7.204915,-4.127467,2.335782,-0.867561,3.391467
1,3.706128,-5.457965,0.963582,-0.867561,1.539053
2,2.857096,0.600705,4.187053,-0.677576,4.161088
3,2.546897,-4.162544,0.283040,-0.867561,0.730206
4,2.435578,-3.465937,0.143240,-0.867561,0.588236
...,...,...,...,...,...
173,-0.692805,0.256358,-0.628027,-0.537928,-0.674534
174,-0.698642,0.269302,-0.866859,-0.299228,-0.881916
175,-0.701963,0.200372,-1.494691,-0.333328,-1.424779
176,-0.707286,0.246736,-0.882885,0.374653,-0.897405


In [152]:
numerical_cols_spotify

['streams', 'stream_change', '7day', 'days', 'viral_score']

In [157]:
print(numerical_cols_spotify[:1])

['streams']


In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   track_name           178 non-null    object
 1   artist_name          178 non-null    object
 2   streams              178 non-null    int64 
 3   stream_change        178 non-null    int64 
 4   7day                 178 non-null    int64 
 5   genre                178 non-null    object
 6   country              178 non-null    object
 7   pos                  178 non-null    int64 
 8   days                 178 non-null    int64 
 9   viral_score          178 non-null    int64 
 10  trend                178 non-null    object
 11  popularity_category  178 non-null    object
 12  longevity            178 non-null    object
dtypes: int64(6), object(7)
memory usage: 18.2+ KB


In [169]:
df.head()

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New


In [170]:
df.describe()

,streams,stream_change,7day,pos,days,viral_score
count,1.780000e+02,1.780000e+02,1.780000e+02,178.000000,178.000000,1.780000e+02
mean,2.093366e+06,-2.719877e+05,1.244096e+07,96.123596,536.275281,1.453433e+07
std,1.277789e+06,7.528285e+05,5.786175e+06,56.151997,617.572830,6.699639e+06
min,1.191777e+06,-4.369341e+06,2.523194e+06,1.000000,2.000000,3.774959e+06
25%,1.350050e+06,-1.267320e+05,9.277907e+06,48.250000,80.000000,1.067544e+07
50%,1.590738e+06,-7.408450e+04,1.080256e+07,96.500000,346.500000,1.257072e+07
75%,2.202585e+06,-5.174750e+03,1.354278e+07,141.750000,766.250000,1.608216e+07
max,1.127383e+07,1.899990e+05,3.659983e+07,200.000000,3070.000000,4.233369e+07
